# Generated by Django 5.0.6 on 2025-07-05 04:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='images',
            field=models.ImageField(blank=True, help_text='Upload complaint image (max 5MB)', null=True, upload_to='media/complaints/', validators=[main.models.validate_image_size]),
        ),
    ]
